version: "3"
services:
  api:
    restart: always
    build: .
    ports:
      - "127.0.0.1:3000:3000"
    depends_on:
      - "db"
    environment:
      NODE_ENV: "production"
      DATABASE_HOST: "db"
      DATABASE_PORT: "27017"
      DATABASE_NAME: "place"
      DATABASE_USER: "root"
      DATABASE_PASSWORD: "root"
      DATABASE_AUTH_SOURCE: "admin"
      PORT: 3000
      ONLY_LISTEN_LOCAL: "false"
  db:
    image: mongo:latest
    restart: always
    volumes:
      - mongo-volume:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: place
    ports:
      - "27017:27017"
volumes:
  mongo-volume:
